
FEATURE_COLS = [
    "PREV_AGE", "PREV_GP", "PREV_MIN", "PREV_PTS", "PREV_REB", "PREV_AST", "PREV_FG_PCT", "PREV_FG3_PCT", "PREV_FT_PCT", "PREV_TS_PCT", "PREV_USG_PCT", "PREV_AST_PCT", "PREV_PIE", "PREV_PTS_PER36", "PREV_REB_PER36", "PREV_AST_PER36",
    # "PREV_FGA_PER36", "PREV_FG3A_PER36", "PREV_FTA_PER36",
    "TEAM_CHANGED",
]

def eligible_mask(df):
    return (df["PREV_AGE"] <= 26) & (df["PREV_GP"] >= 30) & (df["PREV_MIN"] >= 12)
